---
langs: [fr_FR,en_US,es_ES]
baseurl: "/"
sass:
  sass_dir: assets/css
  style: compressed
markdown: kramdown
permalink: /404.html
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
- jekyll-paginate
- jekyll-seo-tag
exclude:
- vendor
plugins:
- jekyll-seo-tag
title: "Documentation Plugins-naEnergie"
description: "Ceci est la documentation du plugin Jeedom naEnergie"
author: "Limad44"
image: https://avatars1.githubusercontent.com/u/36200380?s=200&v=4
social:
  name: Plugins-naEnergie
  links:
    -https://limad.github.io/plugin-naEnergie
